apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm2
  namespace: bbamycoulibaly-dev
  labels:
    app: vm-web
    kubevirt.io/domain: vm2
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm2
    spec:
      domain:
        cpu:
          sockets: 1
          cores: 1
          threads: 1
        resources:
          requests:
            memory: 600Mi
            cpu: 100m # On demande très peu de CPU au démarrage
          limits:
            memory: 600Mi
            cpu: 500m
        devices:
          interfaces:
            - name: default
              masquerade: {}
              ports:
                - port: 80
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
        memory:
          guest: 600Mi
      networks:
        - name: default
          pod: {}
      volumes:
        - containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              user: ubuntu
              password: AmyPass2026
              chpasswd: { expire: False }
              ssh_pwauth: True
          name: cloudinitdisk
