apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm2
  namespace: bbamycoulibaly-dev
  labels:
    app: vm-web
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm2
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
        memory:
          guest: 1Gi
      volumes:
        - containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              user: ubuntu
              password: AmyPass2026
              chpasswd: { expire: False }
              ssh_pwauth: True
              # INSTALLATION AUTOMATIQUE
              packages:
                - nginx
              runcmd:
                - systemctl enable --now nginx
                - echo "<h1>Serveur Web VM2 (DMZ) - Projet Amy</h1>" > /var/www/html/index.html
                - echo "Serveur operationnel" >> /var/www/html/status.txt
          name: cloudinitdisk
