name: Deploy-Infra-Coulibaly-V2
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Installation de l'outil OC
        uses: redhat-actions/oc-installer@v1

      - name: Connexion au Sandbox
        run: |
          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ secrets.OC_SERVER }} --insecure-skip-tls-verify
          
      - name: Etape 1 - Virtualisation
        run: oc apply -f 01-virtualisation/

      - name: Etape 2 - Services (Pod DB)
        run: oc apply -f 02-services/

      - name: Etape 3 - Reseau et Securite
        run: oc apply -f 03-reseau/
